#include "stdafx.h"
#include "KeyCodeMaper.h"

CMap<DWORD, DWORD, CString, CString> CKeyCodeMaper::m_mapKeyToName;

CKeyCodeMaper::CKeyCodeMaper(void)
{
	
}


CKeyCodeMaper::~CKeyCodeMaper(void)
{
}

BOOL CKeyCodeMaper::Lookup(DWORD dwKeyCode, CString& strKeyName)
{
	if(m_mapKeyToName.GetCount() <= 0)
	{
		m_mapKeyToName.SetAt(VK_LBUTTON, _T("VK_LBUTTON"));
		m_mapKeyToName.SetAt(VK_RBUTTON, _T("VK_RBUTTON"));
		m_mapKeyToName.SetAt(VK_CANCEL, _T("VK_CANCEL"));
		m_mapKeyToName.SetAt(VK_MBUTTON, _T("VK_MBUTTON"));
		m_mapKeyToName.SetAt(VK_XBUTTON1, _T("VK_XBUTTON1"));
		m_mapKeyToName.SetAt(VK_XBUTTON2, _T("VK_XBUTTON2"));
		m_mapKeyToName.SetAt(0x07, _T("Reserved 0x07"));
		m_mapKeyToName.SetAt(VK_BACK, _T("VK_BACK"));
		m_mapKeyToName.SetAt(0x0A, _T("Reserved 0x0A"));
		m_mapKeyToName.SetAt(0x0B, _T("Reserved 0x0B"));
		m_mapKeyToName.SetAt(VK_CLEAR, _T("VK_CLEAR"));
		m_mapKeyToName.SetAt(VK_RETURN, _T("VK_RETURN"));
		m_mapKeyToName.SetAt(0x0E, _T("Unassigned 0x0E"));
		m_mapKeyToName.SetAt(0x0F, _T("Unassigned 0x0F"));
		m_mapKeyToName.SetAt(VK_SHIFT, _T("VK_SHIFT"));
		m_mapKeyToName.SetAt(VK_CONTROL, _T("VK_CONTROL"));
		m_mapKeyToName.SetAt(VK_MENU, _T("VK_MENU"));
		m_mapKeyToName.SetAt(VK_PAUSE, _T("VK_PAUSE"));
		m_mapKeyToName.SetAt(VK_CAPITAL, _T("VK_CAPITAL"));
		m_mapKeyToName.SetAt(VK_KANA, _T("VK_KANA"));
		m_mapKeyToName.SetAt(VK_HANGUL, _T("VK_HANGUL"));
		//m_mapKeyToName.SetAt(VK_IME_ON, _T("VK_IME_ON"));
		m_mapKeyToName.SetAt(VK_JUNJA, _T("VK_JUNJA"));
		m_mapKeyToName.SetAt(VK_FINAL, _T("VK_FINAL"));
		m_mapKeyToName.SetAt(VK_HANJA, _T("VK_HANJA"));
		m_mapKeyToName.SetAt(VK_KANJI, _T("VK_KANJI"));
		//m_mapKeyToName.SetAt(VK_IME_OFF, _T("VK_IME_OFF"));
		m_mapKeyToName.SetAt(VK_ESCAPE, _T("VK_ESCAPE"));
		m_mapKeyToName.SetAt(VK_CONVERT, _T("VK_CONVERT"));
		m_mapKeyToName.SetAt(VK_NONCONVERT, _T("VK_NONCONVERT"));
		m_mapKeyToName.SetAt(VK_ACCEPT, _T("VK_ACCEPT"));
		m_mapKeyToName.SetAt(VK_MODECHANGE, _T("VK_MODECHANGE"));
		m_mapKeyToName.SetAt(VK_SPACE, _T("VK_SPACE"));
		m_mapKeyToName.SetAt(VK_PRIOR, _T("VK_PRIOR"));
		m_mapKeyToName.SetAt(VK_NEXT, _T("VK_NEXT"));
		m_mapKeyToName.SetAt(VK_END, _T("VK_END"));
		m_mapKeyToName.SetAt(VK_HOME, _T("VK_HOME"));
		m_mapKeyToName.SetAt(VK_LEFT, _T("VK_LEFT"));
		m_mapKeyToName.SetAt(VK_UP, _T("VK_UP"));
		m_mapKeyToName.SetAt(VK_RIGHT, _T("VK_RIGHT"));
		m_mapKeyToName.SetAt(VK_DOWN, _T("VK_DOWN"));
		m_mapKeyToName.SetAt(VK_SELECT, _T("VK_SELECT"));
		m_mapKeyToName.SetAt(VK_PRINT, _T("VK_PRINT"));
		m_mapKeyToName.SetAt(VK_EXECUTE, _T("VK_EXECUTE"));
		m_mapKeyToName.SetAt(VK_SNAPSHOT, _T("VK_SNAPSHOT"));
		m_mapKeyToName.SetAt(VK_INSERT, _T("VK_INSERT"));
		m_mapKeyToName.SetAt(VK_DELETE, _T("VK_DELETE"));
		m_mapKeyToName.SetAt('0', _T("0"));
		m_mapKeyToName.SetAt('1', _T("1"));
		m_mapKeyToName.SetAt('2', _T("2"));
		m_mapKeyToName.SetAt('3', _T("3"));
		m_mapKeyToName.SetAt('4', _T("4"));
		m_mapKeyToName.SetAt('5', _T("5"));
		m_mapKeyToName.SetAt('6', _T("6"));
		m_mapKeyToName.SetAt('7', _T("7"));
		m_mapKeyToName.SetAt('8', _T("8"));
		m_mapKeyToName.SetAt('9', _T("9"));
		m_mapKeyToName.SetAt('A', _T("A"));
		m_mapKeyToName.SetAt('B', _T("B"));
		m_mapKeyToName.SetAt('C', _T("C"));
		m_mapKeyToName.SetAt('D', _T("D"));
		m_mapKeyToName.SetAt('E', _T("E"));
		m_mapKeyToName.SetAt('F', _T("F"));
		m_mapKeyToName.SetAt('G', _T("G"));
		m_mapKeyToName.SetAt('H', _T("H"));
		m_mapKeyToName.SetAt('I', _T("I"));
		m_mapKeyToName.SetAt('J', _T("J"));
		m_mapKeyToName.SetAt('K', _T("K"));
		m_mapKeyToName.SetAt('L', _T("L"));
		m_mapKeyToName.SetAt('M', _T("M"));
		m_mapKeyToName.SetAt('N', _T("N"));
		m_mapKeyToName.SetAt('O', _T("O"));
		m_mapKeyToName.SetAt('P', _T("P"));
		m_mapKeyToName.SetAt('Q', _T("Q"));
		m_mapKeyToName.SetAt('R', _T("R"));
		m_mapKeyToName.SetAt('S', _T("S"));
		m_mapKeyToName.SetAt('T', _T("T"));
		m_mapKeyToName.SetAt('U', _T("U"));
		m_mapKeyToName.SetAt('V', _T("V"));
		m_mapKeyToName.SetAt('X', _T("X"));
		m_mapKeyToName.SetAt('Y', _T("Y"));
		m_mapKeyToName.SetAt('Z', _T("Z"));
		m_mapKeyToName.SetAt('W', _T("W"));
		m_mapKeyToName.SetAt(VK_LWIN, _T("VK_LWIN"));
		m_mapKeyToName.SetAt(VK_RWIN, _T("VK_RWIN"));
		m_mapKeyToName.SetAt(VK_APPS, _T("VK_APPS"));
		m_mapKeyToName.SetAt(0x5E, _T("rESERVED 0x5E"));
		m_mapKeyToName.SetAt(VK_SLEEP, _T("VK_SLEEP"));
		m_mapKeyToName.SetAt(VK_NUMPAD0, _T("VK_NUMPAD0"));
		m_mapKeyToName.SetAt(VK_NUMPAD1, _T("VK_NUMPAD1"));
		m_mapKeyToName.SetAt(VK_NUMPAD2, _T("VK_NUMPAD2"));
		m_mapKeyToName.SetAt(VK_NUMPAD3, _T("VK_NUMPAD3"));
		m_mapKeyToName.SetAt(VK_NUMPAD4, _T("VK_NUMPAD4"));
		m_mapKeyToName.SetAt(VK_NUMPAD5, _T("VK_NUMPAD5"));
		m_mapKeyToName.SetAt(VK_NUMPAD6, _T("VK_NUMPAD6"));
		m_mapKeyToName.SetAt(VK_NUMPAD7, _T("VK_NUMPAD7"));
		m_mapKeyToName.SetAt(VK_NUMPAD8, _T("VK_NUMPAD8"));
		m_mapKeyToName.SetAt(VK_NUMPAD9, _T("VK_NUMPAD9"));
		m_mapKeyToName.SetAt(VK_MULTIPLY, _T("VK_MULTIPLY"));
		m_mapKeyToName.SetAt(VK_ADD, _T("VK_ADD"));
		m_mapKeyToName.SetAt(VK_SEPARATOR, _T("VK_SEPARATOR"));
		m_mapKeyToName.SetAt(VK_SUBTRACT, _T("VK_SUBTRACT"));
		m_mapKeyToName.SetAt(VK_DECIMAL, _T("VK_DECIMAL"));
		m_mapKeyToName.SetAt(VK_DIVIDE, _T("VK_DIVIDE"));
		m_mapKeyToName.SetAt(VK_F1, _T("VK_F1"));
		m_mapKeyToName.SetAt(VK_F2, _T("VK_F2"));
		m_mapKeyToName.SetAt(VK_F3, _T("VK_F3"));
		m_mapKeyToName.SetAt(VK_F4, _T("VK_F4"));
		m_mapKeyToName.SetAt(VK_F5, _T("VK_F5"));
		m_mapKeyToName.SetAt(VK_F6, _T("VK_F6"));
		m_mapKeyToName.SetAt(VK_F7, _T("VK_F7"));
		m_mapKeyToName.SetAt(VK_F8, _T("VK_F8"));
		m_mapKeyToName.SetAt(VK_F9, _T("VK_F9"));
		m_mapKeyToName.SetAt(VK_F10, _T("VK_F10"));
		m_mapKeyToName.SetAt(VK_F11, _T("VK_F11"));
		m_mapKeyToName.SetAt(VK_F12, _T("VK_F12"));
		m_mapKeyToName.SetAt(VK_F13, _T("VK_F13"));
		m_mapKeyToName.SetAt(VK_F14, _T("VK_F14"));
		m_mapKeyToName.SetAt(VK_F15, _T("VK_F15"));
		m_mapKeyToName.SetAt(VK_F16, _T("VK_F16"));
		m_mapKeyToName.SetAt(VK_F17, _T("VK_F17"));
		m_mapKeyToName.SetAt(VK_F18, _T("VK_F18"));
		m_mapKeyToName.SetAt(VK_F19, _T("VK_F19"));
		m_mapKeyToName.SetAt(VK_F20, _T("VK_F20"));
		m_mapKeyToName.SetAt(VK_F21, _T("VK_F21"));
		m_mapKeyToName.SetAt(VK_F22, _T("VK_F22"));
		m_mapKeyToName.SetAt(VK_F23, _T("VK_F23"));
		m_mapKeyToName.SetAt(VK_F24, _T("VK_F24"));
		m_mapKeyToName.SetAt(VK_NUMLOCK, _T("VK_NUMLOCK"));
		m_mapKeyToName.SetAt(VK_SCROLL, _T("VK_SCROLL"));
		m_mapKeyToName.SetAt(0x092, _T("OEM specific 0x092"));
		m_mapKeyToName.SetAt(0x093, _T("OEM specific 0x093"));
		m_mapKeyToName.SetAt(0x094, _T("OEM specific 0x094"));
		m_mapKeyToName.SetAt(0x095, _T("OEM specific 0x095"));
		m_mapKeyToName.SetAt(0x096, _T("OEM specific 0x096"));
		m_mapKeyToName.SetAt(0x097, _T("Unassigned 0x097"));
		m_mapKeyToName.SetAt(0x098, _T("Unassigned 0x098"));
		m_mapKeyToName.SetAt(0x099, _T("Unassigned 0x099"));
		m_mapKeyToName.SetAt(0x09A, _T("Unassigned 0x09A"));
		m_mapKeyToName.SetAt(0x09B, _T("Unassigned 0x09B"));
		m_mapKeyToName.SetAt(0x09C, _T("Unassigned 0x09C"));
		m_mapKeyToName.SetAt(0x09D, _T("Unassigned 0x09D"));
		m_mapKeyToName.SetAt(0x09E, _T("Unassigned 0x09E"));
		m_mapKeyToName.SetAt(0x09F, _T("Unassigned 0x09F"));
		m_mapKeyToName.SetAt(VK_LSHIFT, _T("VK_LSHIFT"));
		m_mapKeyToName.SetAt(VK_RSHIFT, _T("VK_RSHIFT"));
		m_mapKeyToName.SetAt(VK_LCONTROL, _T("VK_LCONTROL"));
		m_mapKeyToName.SetAt(VK_RCONTROL, _T("VK_RCONTROL"));
		m_mapKeyToName.SetAt(VK_LMENU, _T("VK_LMENU"));
		m_mapKeyToName.SetAt(VK_RMENU, _T("VK_RMENU"));
		m_mapKeyToName.SetAt(VK_BROWSER_BACK, _T("VK_BROWSER_BACK"));
		m_mapKeyToName.SetAt(VK_BROWSER_FORWARD, _T("VK_BROWSER_FORWARD"));
		m_mapKeyToName.SetAt(VK_BROWSER_REFRESH, _T("VK_BROWSER_REFRESH"));
		m_mapKeyToName.SetAt(VK_BROWSER_STOP, _T("VK_BROWSER_STOP"));
		m_mapKeyToName.SetAt(VK_BROWSER_SEARCH, _T("VK_BROWSER_SEARCH"));
		m_mapKeyToName.SetAt(VK_BROWSER_FAVORITES, _T("VK_BROWSER_FAVORITES"));
		m_mapKeyToName.SetAt(VK_BROWSER_HOME, _T("VK_BROWSER_HOME"));
		m_mapKeyToName.SetAt(VK_VOLUME_MUTE, _T("VK_VOLUME_MUTE"));
		m_mapKeyToName.SetAt(VK_VOLUME_DOWN, _T("VK_VOLUME_DOWN"));
		m_mapKeyToName.SetAt(VK_VOLUME_UP, _T("VK_VOLUME_UP"));
		m_mapKeyToName.SetAt(VK_MEDIA_NEXT_TRACK, _T("VK_MEDIA_NEXT_TRACK"));
		m_mapKeyToName.SetAt(VK_MEDIA_PREV_TRACK, _T("VK_MEDIA_PREV_TRACK"));
		m_mapKeyToName.SetAt(VK_MEDIA_STOP, _T("VK_MEDIA_STOP"));
		m_mapKeyToName.SetAt(VK_MEDIA_PLAY_PAUSE, _T("VK_MEDIA_PLAY_PAUSE"));
		m_mapKeyToName.SetAt(VK_LAUNCH_MAIL, _T("VK_LAUNCH_MAIL"));
		m_mapKeyToName.SetAt(VK_LAUNCH_MEDIA_SELECT, _T("VK_LAUNCH_MEDIA_SELECT"));
		m_mapKeyToName.SetAt(VK_LAUNCH_APP1, _T("VK_LAUNCH_APP1"));
		m_mapKeyToName.SetAt(VK_LAUNCH_APP2, _T("VK_LAUNCH_APP2"));
		m_mapKeyToName.SetAt(0x0B8, _T("Reserved 0xB8"));
		m_mapKeyToName.SetAt(0x0B9, _T("Reserved 0x0B9"));
		m_mapKeyToName.SetAt(VK_OEM_1, _T("VK_OEM_1"));
		m_mapKeyToName.SetAt(VK_OEM_PLUS, _T("VK_OEM_PLUS"));
		m_mapKeyToName.SetAt(VK_OEM_COMMA, _T("VK_OEM_COMMA"));
		m_mapKeyToName.SetAt(VK_OEM_MINUS, _T("VK_OEM_MINUS"));
		m_mapKeyToName.SetAt(VK_OEM_PERIOD, _T("VK_OEM_PERIOD"));
		m_mapKeyToName.SetAt(VK_OEM_2, _T("VK_OEM_2"));
		m_mapKeyToName.SetAt(VK_OEM_3, _T("VK_OEM_3"));
		m_mapKeyToName.SetAt(VK_OEM_4, _T("VK_OEM_4"));
		m_mapKeyToName.SetAt(VK_OEM_5, _T("VK_OEM_5"));
		m_mapKeyToName.SetAt(VK_OEM_6, _T("VK_OEM_6"));
		m_mapKeyToName.SetAt(VK_OEM_7, _T("VK_OEM_7"));
		m_mapKeyToName.SetAt(VK_OEM_8, _T("VK_OEM_8"));
		m_mapKeyToName.SetAt(VK_OEM_102, _T("VK_OEM_102"));
		m_mapKeyToName.SetAt(VK_PROCESSKEY, _T("VK_PROCESSKEY"));
		m_mapKeyToName.SetAt(VK_PACKET, _T("VK_PACKET"));
		m_mapKeyToName.SetAt(0xE8, _T("Unassigned 0xE8"));
		m_mapKeyToName.SetAt(0xE9, _T("OEM specific 0xE9"));
		m_mapKeyToName.SetAt(0xEA, _T("OEM specific 0xEA"));
		m_mapKeyToName.SetAt(0xEB, _T("Unassigned 0xEB"));
		m_mapKeyToName.SetAt(0xEC, _T("Unassigned 0xEC"));
		m_mapKeyToName.SetAt(0xED, _T("Unassigned 0xED"));
		m_mapKeyToName.SetAt(0xEE, _T("Unassigned 0xEE"));
		m_mapKeyToName.SetAt(0xEF, _T("Unassigned 0xEF"));
		m_mapKeyToName.SetAt(0xF0, _T("Unassigned 0xF0"));
		m_mapKeyToName.SetAt(0xF1, _T("Unassigned 0xF1"));
		m_mapKeyToName.SetAt(0xF2, _T("Unassigned 0xF2"));
		m_mapKeyToName.SetAt(0xF3, _T("Unassigned 0xF3"));
		m_mapKeyToName.SetAt(0xF4, _T("Unassigned 0xF4"));
		m_mapKeyToName.SetAt(0xF5, _T("Unassigned 0xF5"));
		m_mapKeyToName.SetAt(VK_ATTN, _T("VK_ATTN"));
		m_mapKeyToName.SetAt(VK_CRSEL, _T("VK_CRSEL"));
		m_mapKeyToName.SetAt(VK_EXSEL, _T("VK_EXSEL"));
		m_mapKeyToName.SetAt(VK_EREOF, _T("VK_EREOF"));
		m_mapKeyToName.SetAt(VK_PLAY, _T("VK_PLAY"));
		m_mapKeyToName.SetAt(VK_ZOOM, _T("VK_ZOOM"));
		m_mapKeyToName.SetAt(VK_NONAME, _T("VK_NONAME"));
		m_mapKeyToName.SetAt(VK_PA1, _T("VK_PA1"));
		m_mapKeyToName.SetAt(VK_OEM_CLEAR, _T("VK_OEM_CLEAR"));
	}

	return m_mapKeyToName.Lookup(dwKeyCode, strKeyName);
}